[package]
name = "rust_tools"
version = "0.1.0"
authors = ["Dan <circa.1991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.0"
http = "0.2"
